version: "3.2"

services:
  my_database:
    image: mysql:8.0
    restart: always
    environment:
      - MYSQL_DATABASE=tasks
      - MYSQL_USER=cesar
      - MYSQL_PASSWORD=cesar
    ports:
      - 3336:3306